name: Codecov Workflow

on: [push, pull_request]

jobs:
  build:
    name: "Run pytest with cov (OS: ${{ matrix.os }} | Py: ${{ matrix.python }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable
          install-chromedriver: true

      - name: Show Chrome versions
        run: |
          "${{ steps.setup-chrome.outputs.chrome-path }}" --version
          "${{ steps.setup-chrome.outputs.chromedriver-path }}" --version
        shell: bash

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          pip install . --upgrade
        shell: bash

      - name: Run tests and collect coverage
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
          CHROMEDRIVER: ${{ steps.setup-chrome.outputs.chromedriver-path }}
        run: |
          coverage run -m pytest
          coverage xml
        shell: bash

      - name: Upload coverage reports to Codecov
        if: matrix.os == 'macos-latest' && matrix.python == '3.10'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: rmj3197/SurVigilance
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true
