name: Codecov Workflow

on:
  push:
  pull_request:
  schedule:
    # Every 14 days at 00:00 UTC
    - cron: "0 0 * * *"

jobs:
  build:
    name: "Run pytest with cov (OS: ${{ matrix.os }} | Py: ${{ matrix.python }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python: ['3.11']

    steps:
      - uses: actions/checkout@v4

      - name: List files in repository root
        run: |
          echo "Files in root directory:"
          ls -la
        shell: bash

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable
          install-chromedriver: true

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          pip install . --upgrade
        shell: bash

      - name: Run tests and collect coverage
        working-directory: .
        run: |
          coverage run --rcfile=ci.coveragerc -m pytest .
          coverage xml --rcfile=ci.coveragerc
        shell: bash

      - name: Upload coverage reports to Codecov
        if: matrix.os == 'macos-latest' && matrix.python == '3.11'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: rmj3197/SurVigilance
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true
